# **Exercise 3: Multiple Linear Regression**
**Sancon, Simon B.**

**BSCS-IS-3B**

# **1.Importing Libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# **2. Creating a Synthethic Dataset**

In [ ]:
np.random.seed() #For Reproducability
x = np.random.rand(100,3) #
y = x[:,0] * 150000 + x[:,1] * 100000 + x[:,2] * 50000 + 50000

# **3. Converting to a DataFrame**

In [ ]:
data = pd.DataFrame(x, columns = ['Size', 'Bedrooms', 'Age'])
data['Price'] = y

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)
data.head()

Size  Bedrooms       Age          Price
0  0.708869  0.502764  0.990989  256156.307581
1  0.928360  0.474403  0.393767  256382.700931
2  0.626142  0.389186  0.706762  218177.931603
3  0.741277  0.560027  0.880651  261226.769231
4  0.781289  0.505647  0.141239  224819.975521

# **4. Initializing the Model**

In [ ]:
model = LinearRegression()

# **5. Fitting the Model**

In [ ]:
model.fit(x_train, y_train)

LinearRegression()

# **6. Making Predictions**

In [ ]:
y_predict = model.predict(x_test)
print(x_test)
print(y_predict)

[[0.27958075 0.50094842 0.50202551]
 [0.33934516 0.38778924 0.71676053]
 [0.44333354 0.15593732 0.48383121]
 [0.28641191 0.83848349 0.48105423]
 [0.83215827 0.17306123 0.67707438]
 [0.42162608 0.8519738  0.34057331]
 [0.48128985 0.3963811  0.46747426]
 [0.05529394 0.07461177 0.64051448]
 [0.55051988 0.17260744 0.28535349]
 [0.7088693  0.50276442 0.99098943]
 [0.5530117  0.87348816 0.50344578]
 [0.40168993 0.6500401  0.56290203]
 [0.18111246 0.43600335 0.62638392]
 [0.70749177 0.47323853 0.87044988]
 [0.50452909 0.00775573 0.63340037]
 [0.78128913 0.50564653 0.14123907]
 [0.76497324 0.86010593 0.5284618 ]
 [0.92811453 0.6683227  0.91150944]
 [0.83174658 0.20122344 0.53843097]
 [0.02473058 0.23017233 0.74453203]]
[167133.23010839 175518.72435436 156285.32382552 200862.84697302
 225983.58227035 215469.95840372 185205.30013074  97780.99172852
 164106.40121872 256156.30758052 245472.85881531 203402.60040717
 152086.40046536 246970.11260132 158124.95402749 224819.9755214
 277179.66886776 301

# **7. Calculating the Mean Squared Error**

In [ ]:
mse= mean_squared_error(y_test,y_predict)
print("Mean Squared Error", mse)

Mean Squared Error 2.3822801641527197e-21


# **8. Predicting the Price of a New House**

In [ ]:
new_house = [[0.5,2,10]]
predicted_price = model.predict(new_house)
print(f"Predicted: , {predicted_price[0]}")

Predicted: , 824999.9999999999
